const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path');
const root=path.join(__dirname,'..');
let rows=[['topicId','title','description','imageEnabled','commentEnabled','isActive','extra'],['tiling','敷き詰めパターン','既存',true,true,true,'keep'],['legacy','既存2','説明',false,false,false,'extra preserved']];
let active='owner@example.test',effective=active,locked=false,writes=0;
const sheet={getLastColumn:()=>rows[0].length,getLastRow:()=>rows.length,getRange:(r,c,h,w)=>({getValues:()=>Array.from({length:h},(_,i)=>Array.from({length:w},(_,j)=>rows[r-1+i]?.[c-1+j]??'')),setValues:values=>{writes++;for(let i=0;i<h;i++){rows[r-1+i]??=[];for(let j=0;j<w;j++)rows[r-1+i][c-1+j]=values[i][j];}}})};
const ctx=vm.createContext({PropertiesService:{getScriptProperties:()=>({getProperty:k=>k==='SPREADSHEET_ID'?'test-sheet':'owner@example.test'})},Session:{getActiveUser:()=>({getEmail:()=>active}),getEffectiveUser:()=>({getEmail:()=>effective})},SpreadsheetApp:{openById:()=>({getSheetByName:name=>{assert.equal(name,'Topics');return sheet;}}),flush:()=>{}},LockService:{getScriptLock:()=>({tryLock:()=>{if(locked)return false;locked=true;return true;},releaseLock:()=>{locked=false;}})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,s)=>crypto.createHash('sha256').update(s).digest(),base64EncodeWebSafe:b=>Buffer.from(b).toString('base64url')}});
for(const f of ['Config.gs','TopicsService.gs'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);
const invoke=(name,input)=>JSON.parse(JSON.stringify(ctx[name](input)));
const originalTiling=JSON.stringify(rows[1]);
assert.equal(invoke('adminListTopics').data.length,2);
let added=invoke('adminCreateTopic',{topicId:'ambigram',title:'アンビグラム',description:'文字の探究'});assert.equal(added.ok,true);assert.equal(added.data.isActive,false);assert.equal(added.data.imageEnabled,true);assert.equal(added.data.commentEnabled,true);
assert.equal(invoke('adminCreateTopic',{topicId:'ambigram',title:'再送',description:''}).error.code,'DUPLICATE');assert.equal(rows.length,4);
for(const input of [{topicId:'../bad',title:'a',description:''},{topicId:'unsafe',title:'=IMPORTXML("x")',description:''},{topicId:'flags',title:'a',description:'',imageEnabled:false}])assert.equal(invoke('adminCreateTopic',input).ok,false);
let item=invoke('adminListTopics').data.find(t=>t.topicId==='legacy');
const update={topicId:item.topicId,title:'変更後',description:'更新',isActive:true,revision:item.revision};
let result=invoke('adminUpdateTopic',update);assert.equal(result.ok,true);assert.equal(result.data.imageEnabled,false);assert.equal(result.data.commentEnabled,false);assert.equal(rows[2][6],'extra preserved');assert.equal(rows[2][0],'legacy');assert.equal(rows[2][5],true);
assert.equal(invoke('adminUpdateTopic',update).error.code,'CONFLICT');
result=invoke('adminUpdateTopic',{...update,revision:result.data.revision,isActive:false});assert.equal(result.ok,true);assert.equal(rows[2][5],false);
const tiling=invoke('adminListTopics').data.find(t=>t.topicId==='tiling');assert.equal(invoke('adminUpdateTopic',{topicId:'tiling',title:'changed',description:'',isActive:false,revision:tiling.revision}).error.code,'PROTECTED');assert.equal(JSON.stringify(rows[1]),originalTiling);
assert.equal(invoke('adminUpdateTopic',{...update,topicId:'renamed-id'}).error.code,'NOT_FOUND');
const writeCount=writes;active='student@example.test';assert.equal(invoke('adminListTopics').error.code,'FORBIDDEN');assert.equal(invoke('adminCreateTopic',{topicId:'student',title:'x',description:''}).error.code,'FORBIDDEN');active='';assert.equal(invoke('adminListTopics').error.code,'FORBIDDEN');active=effective;assert.equal(writes,writeCount);
locked=true;assert.equal(invoke('adminCreateTopic',{topicId:'busy',title:'x',description:''}).error.code,'BUSY');locked=false;
rows[0][0]='wrong';assert.equal(invoke('adminListTopics').error.code,'SCHEMA');assert.equal(writes,writeCount);
console.log('PASS schema, auth, add, defaults, duplicate, lock contention, edit, flags, protected tiling, extra columns, conflict, visibility');
